### ISSUE TITLE
is anonymous not being counted?

### ISSUE THREAD

**Issue by HDRorz** [loggerhead/vote_against_37#2]
if use doAnonymousLogin
it could be
_ZVING_METHOD:Register.doAnonymousLogin
_ZVING_URL:%2Findex
_ZVING_DATA:{"userName":"","province":"上海市","job":"IT|互联网|通信","email":"","mobile":"","address":""}
_ZVING_DATA_FORMAT:json

**Comment by loggerhead** [comment]
See https://github.com/loggerhead/vote_against_37/pull/1#issuecomment-203184836
