### ISSUE TITLE
官网已推出验证码功能

### ISSUE THREAD

**Issue by owenyang0** [loggerhead/vote_against_37#4]
虽然投票不一定被记录，但如果使用的人足够多，至少可以DDOS一下。

所以，有没有哪位被验证码的功能给做了？**拜谢！**
![image](https://cloud.githubusercontent.com/assets/2222167/14137844/534eb0c4-f69c-11e5-80aa-a0af414d1af4.png)

**Comment by loggerhead** [comment]
@owenyang0 
1. DDOS 政府网站没意义，国家机器支持的网站即使被 D 挂了，政策照样会通过，唉。
2. 验证码没法做，图像处理本身就是比较麻烦的事情，除非它的验证码很简单。

**Comment by MtZero** [comment]
现在文件的页面也已经进不去了，一点击就会让你返回首页登录。其他页面可以进去。

**Comment by loggerhead** [comment]
@MtZero ╮(╯_╰)╭

**Comment by owenyang0** [comment]
昨天看到一个新闻：ZF说，37号政策的推出不会影响任何人任何公司，所以大家不用在意。
我就在想，如果这一项规定99%的人都反对，还搞一个所谓的“民主”投票，最后还要强行实施，这样的民主简直是。。。
